version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.1
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
